### ISSUE TITLE
where is WorkflowUtilization.xlsx?

### ISSUE THREAD

**Issue by xlq246860** [sajithgeopaul/application-execution-time-prediction#1]
hello, I am wondering how to relate the execution time to the runtime or pre-runtime parameters in workflow.py and BLSTM.py. and where is the workflowUtilization.xlsx  app.py? Thanks for your help.

**Comment by sajithgeopaul** [comment]
The code in workflow.py uses GRU machine learning method. However if you were to run it and observe the outputs, you will realize that both pre-run and run-time parameters contain a number of parameters making it difficult to obtain the desired target value. Hence, the outputs from the machine learning method are used to just to find a relation between all the parameters. The code and the dataset used only takes into account the data generated from trace of an Azure VM. If relating between the parameters are to be made more practical, it requires use of multiple datasets. The code I posted is just an approach which would function better in presence of more accurate VM trace data. As for the workflowUtilization.xlsx, I'll include it into the repo soon.

**Comment by xlq246860** [comment]
Seen the title of this project, I thought it was about execution time prediction of an application or workflow tasks. But after I saw the whole project source code, I found I was mistaken. In my opinion, this project based on time series predicts pre-runtime or runtime parameters and utilization rate. I also learned a lot from this project. And thank the author very much for answering my question.

**Comment by xlq246860** [comment]
> The code in workflow.py uses GRU machine learning method. However if you were to run it and observe the outputs, you will realize that both pre-run and run-time parameters contain a number of parameters making it difficult to obtain the desired target value. Hence, the outputs from the machine learning method are used to just to find a relation between all the parameters. The code and the dataset used only takes into account the data generated from trace of an Azure VM. If relating between the parameters are to be made more practical, it requires use of multiple datasets. The code I posted is just an approach which would function better in presence of more accurate VM trace data. As for the workflowUtilization.xlsx, I'll include it into the repo soon.

Seen the title of this project, I thought it was about execution time prediction of an application or workflow tasks. But after I saw the whole project source code, I found I was mistaken. In my opinion, this project based on time series predicts pre-runtime or runtime parameters and utilization rate. I also learned a lot from this project. And thank the author very much for answering my question.
